### ISSUE TITLE
User can search for an intersection using a text field

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-sv-vision-zero#16]

**Comment by fitnr** [comment]
What about searching by neighborhood? to discuss.

**Comment by andycochran** [comment]
Here's a set of screenshots of the search UI. 

![vz-search-workflow](https://cloud.githubusercontent.com/assets/409279/3272281/ae35bf40-f316-11e3-89f5-073021b135d8.jpg)

**Comment by fitnr** [comment]
@andycochran this looks great!
