### ISSUE TITLE
Try switching to terrain base tiles

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-sv-vision-zero#25]
Will show streets better.

**Comment by atogle** [comment]
@fkh It looks like terrain tiles restrict our max zoom to 15, which I suspect is not detailed enough.

**Comment by fkh** [comment]
@atogle can we switch to regular street tiles at zooms higher than 15?

If not, let's put custom tiles on the list for next week

**Comment by atogle** [comment]
Custom tiles added.
