### ISSUE TITLE
Some intersections missing

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-sv-vision-zero#26]
@fitnr it seems like we are missing data for some intersections, e.g. Greenwich and Vestry. Is this because these locations have no recorded crashes? Because they are missing in the file, we don't have names for them.

**Comment by fitnr** [comment]
@fkh Seth, who prepared the data, is out today, but I assume you're right. I'm exporting a new set from LION tamed and will send a list with names shortly.
