### ISSUE TITLE
User doesn't understand that they must drag the marker to save a place

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-sv-vision-zero#30]

**Comment by fkh** [comment]
- don't require map drag before submit
- show a prompt about dragging near the submit button

**Comment by fitnr** [comment]
A related issue: dragging streetview away from the icon hides the icon. Is there a way to detect if it's invisible, and slowly slide it in?

**Comment by fitnr** [comment]
Suggestion from Jesse: Add a tooltip to the marker saying "Drag me to the spot where the issue occurs." This should default to being visible, and go away ondrag. (Perhaps it could be hidden for the second issue per session, but whatever)

**Comment by fkh** [comment]
@fitnr thanks - we're mocking this up.
