### ISSUE TITLE
Only show locations that are linked to the current intersection

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-sv-vision-zero#32]
Currently using a distance filter, because that is fast. We should instead pull out locations with matching ids to the intersection and only show those. 

Until we do this, there will be a few rogue points showing up from the next intersection over.

**Comment by fitnr** [comment]
I'm a little surprised that a distance filter is faster than matching IDs.

**Comment by fkh** [comment]
@fitnr id is in a json blob attached to each object, whereas lat/lon are native fields. We are working on indexing the blob contents, but right now we have to look inside the attached json for each record to check the id when doing a query.

**Comment by fkh** [comment]
Not a big problem, no need to fix.
