### ISSUE TITLE
Make small map larger on streetview screen

### ISSUE THREAD

**Issue by fitnr** [openplans/shareabouts-sv-vision-zero#33]
It's a little cramped, and there's lots of whitespace, even on the intersections with issues.

**Comment by fkh** [comment]
@fitnr ok, on it.

**Comment by fkh** [comment]
@fitnr how do you feel about this? 
![screenshot 2014-05-22 13 11 13](https://cloud.githubusercontent.com/assets/389766/3057271/4555b00a-e1d4-11e3-8e17-8cdadacb1a88.png)

**Comment by fitnr** [comment]
That looks good, assuming that the stats at bottom right won't ever appear cut off.
