### ISSUE TITLE
Bug: message about moving marker is off-screen when trying to submit

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-sv-vision-zero#37]
If you fill out the form and click submit, we are showing a prompt to move the marker. But this prompt is scrolled upscreen. We can move the prompt above the submit button to deal with it.

**Comment by fitnr** [comment]
I confess that I don't understand exactly what's happening here.

**Comment by fkh** [comment]
@fitnr we fixed it already.

We're showing a prompt about moving your marker within street view, requiring people to do this before they can submit. But before, we were showing the message at the top of the new place form, which was scrolled out of sight by the time you're clicking submit. Moving the message down dealt with this.
