### ISSUE TITLE
Style: Share and issue form aligns with right col

### ISSUE THREAD

**Issue by fitnr** [openplans/shareabouts-sv-vision-zero#45]
Currently it leaves a gap at the top of the form and extends into the footer.

![screen shot 2014-05-29 at 4 37 22 pm](https://cloud.githubusercontent.com/assets/714125/3123300/61e5f372-e771-11e3-9626-d41d9a20fe4b.png)

**Comment by fkh** [comment]
@fitnr we weren't able to reproduce this bug, but we made some fixes to the layout and resolved a bug we found. Has hopefully taken care of this. Let me know if not.
