### ISSUE TITLE
User has difficulty getting back from individual place view to map

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts-sv-vision-zero#51]
If you click on a marker on the big map, you get taken to the map. From there, you see the place detail "X" close button, but its function is not clear for first time users.

We could make the "full map" button clearer, and show it all the time there's a place open. Maybe as a strip along the top of the place info, with "show larger map"/"back to map" depending on context.

**Comment by fitnr** [comment]
I think a strip with "larger map" at top would work.

**Comment by fitnr** [comment]
The "full map" button seems to be working well.
