### ISSUE TITLE
Better iPad support

### ISSUE THREAD

**Issue by fitnr** [openplans/shareabouts-sv-vision-zero#52]
This is a design issue, the screen real estate just isn't there. Perhaps we can push down the footer and/or use smaller type on the right sidebar?

![ios simulator screen shot jun 12 2014 9 32 10 am](https://cloud.githubusercontent.com/assets/714125/3258127/fd00fa54-f235-11e3-8976-b62ff61d32c8.png)

**Comment by fkh** [comment]
@fitnr we will make the map container larger at each break point, so it pushes the footer right down (we'll just show a tiny sliver of black at the bottom).

Can you change the breakpoint to switch to your mobile header sooner, so landscape tablets get the same header as smaller screens?

**Comment by fitnr** [comment]
I'll look into changing that CSS. It's DOITT's baby, but I think I can make a guerilla edit.

**Comment by fkh** [comment]
@fitnr we made the map bigger to push the footer down. Do you want a dist with this right now, or wait until you've adjusted the header? We will need to adjust the map container again once we know the header dimensions.

**Comment by fitnr** [comment]
@fkh I don't think I can edit the header. It's the same size on both iPad orientations. The breakpoint is for much smaller screens. There isn't a solution there without doing much deeper surgery.

**Comment by fkh** [comment]
@fitnr we are packing up the modified map/smaller footer into a dist now.

Do you want to get together with @andycochran next week to talk about
options here, maybe with someone from DOITT? They could reduce the header
size on ipads, or we could add a button to hide all other chrome on the
page, or something else.

On Thu, Jun 12, 2014 at 3:57 PM, Neil Freeman notifications@github.com
wrote:

> @fkh https://github.com/fkh I don't think I can edit the header. It's
> the same size on both iPad orientations. The breakpoint is for much smaller
> screens. There isn't a solution there without doing much deeper surgery.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openplans/shareabouts-sv-vision-zero/issues/52#issuecomment-45940287
> .

## 

Frank Hebbert
OpenPlans | http://openplans.org | 720 432-2378 | @fkh

**Comment by fitnr** [comment]
I don't think talking to DOITT is realistic in this time frame. A full-screen button is probably best.

**Comment by fitnr** [comment]
@fkh bump.

**Comment by fkh** [comment]
@fitnr do you know what ipad version is being used at meetings -- we will work on a full screen layout that's specific to the screen dimensions.

**Comment by fitnr** [comment]
I would target full-size retina iPad
